# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_landit.ui'
#
# Created: Tue Mar 26 08:46:30 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_LandIt(object):
    def setupUi(self, LandIt):
        LandIt.setObjectName(_fromUtf8("LandIt"))
        LandIt.resize(403, 297)
        self.gridLayout = QtGui.QGridLayout(LandIt)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.widget_2 = QtGui.QWidget(LandIt)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.widget_2)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_4 = QtGui.QLabel(self.widget_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.dtmLayer = QtGui.QComboBox(self.widget_2)
        self.dtmLayer.setObjectName(_fromUtf8("dtmLayer"))
        self.gridLayout_3.addWidget(self.dtmLayer, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.widget_2, 0, 0, 1, 3)
        self.processOnlySelected = QtGui.QCheckBox(LandIt)
        self.processOnlySelected.setObjectName(_fromUtf8("processOnlySelected"))
        self.gridLayout.addWidget(self.processOnlySelected, 8, 0, 1, 3)
        self.widget_3 = QtGui.QWidget(LandIt)
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.gridLayout_4 = QtGui.QGridLayout(self.widget_3)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.vectorLayer = QtGui.QComboBox(self.widget_3)
        self.vectorLayer.setObjectName(_fromUtf8("vectorLayer"))
        self.gridLayout_4.addWidget(self.vectorLayer, 1, 1, 1, 1)
        self.label = QtGui.QLabel(self.widget_3)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_4.addWidget(self.label, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.widget_3, 1, 0, 1, 3)
        self.processOnlyNull = QtGui.QCheckBox(LandIt)
        self.processOnlyNull.setObjectName(_fromUtf8("processOnlyNull"))
        self.gridLayout.addWidget(self.processOnlyNull, 7, 0, 1, 3)
        self.widget_4 = QtGui.QWidget(LandIt)
        self.widget_4.setObjectName(_fromUtf8("widget_4"))
        self.gridLayout_5 = QtGui.QGridLayout(self.widget_4)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.interpolationMethod = QtGui.QComboBox(self.widget_4)
        self.interpolationMethod.setObjectName(_fromUtf8("interpolationMethod"))
        self.interpolationMethod.addItem(_fromUtf8(""))
        self.interpolationMethod.addItem(_fromUtf8(""))
        self.interpolationMethod.addItem(_fromUtf8(""))
        self.gridLayout_5.addWidget(self.interpolationMethod, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.widget_4)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_5.addWidget(self.label_3, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.widget_4, 5, 0, 1, 3)
        self.widget = QtGui.QWidget(LandIt)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.widget)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.destinationField = QtGui.QComboBox(self.widget)
        self.destinationField.setObjectName(_fromUtf8("destinationField"))
        self.gridLayout_2.addWidget(self.destinationField, 1, 3, 1, 1)
        self.label_2 = QtGui.QLabel(self.widget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.widget, 4, 0, 1, 3)
        self.widget_5 = QtGui.QWidget(LandIt)
        self.widget_5.setObjectName(_fromUtf8("widget_5"))
        self.gridLayout_6 = QtGui.QGridLayout(self.widget_5)
        self.gridLayout_6.setMargin(0)
        self.gridLayout_6.setMargin(0)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_5 = QtGui.QLabel(self.widget_5)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_6.addWidget(self.label_5, 0, 0, 1, 1)
        self.additionValue = QtGui.QDoubleSpinBox(self.widget_5)
        self.additionValue.setMinimum(-999.99)
        self.additionValue.setMaximum(999.99)
        self.additionValue.setObjectName(_fromUtf8("additionValue"))
        self.gridLayout_6.addWidget(self.additionValue, 0, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem, 0, 2, 1, 1)
        self.gridLayout.addWidget(self.widget_5, 6, 0, 1, 3)
        self.progressBar = QtGui.QProgressBar(LandIt)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.gridLayout.addWidget(self.progressBar, 11, 0, 1, 1)
        self.messageLabel = QtGui.QLabel(LandIt)
        self.messageLabel.setObjectName(_fromUtf8("messageLabel"))
        self.gridLayout.addWidget(self.messageLabel, 10, 0, 1, 2)
        self.doButton = QtGui.QPushButton(LandIt)
        self.doButton.setObjectName(_fromUtf8("doButton"))
        self.gridLayout.addWidget(self.doButton, 10, 2, 1, 1)
        self.stopButton = QtGui.QPushButton(LandIt)
        self.stopButton.setObjectName(_fromUtf8("stopButton"))
        self.gridLayout.addWidget(self.stopButton, 11, 2, 1, 1)

        self.retranslateUi(LandIt)
        self.interpolationMethod.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(LandIt)

    def retranslateUi(self, LandIt):
        LandIt.setWindowTitle(QtGui.QApplication.translate("LandIt", "LandIt", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("LandIt", "DTM", None, QtGui.QApplication.UnicodeUTF8))
        self.processOnlySelected.setText(QtGui.QApplication.translate("LandIt", "process only selected features", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("LandIt", "Points from layer", None, QtGui.QApplication.UnicodeUTF8))
        self.processOnlyNull.setText(QtGui.QApplication.translate("LandIt", "process features only where destination field is NULL", None, QtGui.QApplication.UnicodeUTF8))
        self.interpolationMethod.setItemText(0, QtGui.QApplication.translate("LandIt", "nearest neighbor", None, QtGui.QApplication.UnicodeUTF8))
        self.interpolationMethod.setItemText(1, QtGui.QApplication.translate("LandIt", "bi-linear", None, QtGui.QApplication.UnicodeUTF8))
        self.interpolationMethod.setItemText(2, QtGui.QApplication.translate("LandIt", "bi-cubic", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("LandIt", "Interpolation method", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("LandIt", "Destination field", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("LandIt", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.messageLabel.setText(QtGui.QApplication.translate("LandIt", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.doButton.setText(QtGui.QApplication.translate("LandIt", "GO", None, QtGui.QApplication.UnicodeUTF8))
        self.stopButton.setText(QtGui.QApplication.translate("LandIt", "Stop", None, QtGui.QApplication.UnicodeUTF8))

